# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kedru.github.io" # the base hostname & protocol for your site
permalink: pretty

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Andrew Meredith"
  # avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "coding, startups, and software engineering"

  # Header and footer text
  header_text: >
     <p>You had nothing to say about it and yet made the nothing up into words</p>

     <p>-- C.S. Lewis, <em>Perelandra</em></p>
  footer_text: >
   Copyright (c) 2015 Andrew Meredith

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  github: "kendru"
  linkedin: http://www.linkedin.com/in/andrewsmeredith
  twitter: "asmeredith"

  # Scripts
  google_analytics: "UA-47033457-1"
  disqus_shortname: kendru
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  feedurl: http://feeds.feedburner.com/kendru-write

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
